{{- if .Values.datavis.prReminderChannelScheduler.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.datavis.prReminderChannelScheduler.name }}
  labels:
{{ include "datavis.labels" . | indent 4 }}
spec:
  replicas: {{ index .Values.datavis.prReminderChannelScheduler.replicaCount }}
  selector:
    matchLabels:
        {{- include "datavis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "datavis.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-dev
          env:
          - name: MONGO_URL
            valueFrom:
              secretKeyRef:
                key: MONGO_URL
                name: sealed-secret-datavis-release
          - name: BITBUCKET_PASSWORD
            valueFrom:
              secretKeyRef:
                key: BITBUCKET_PASSWORD
                name: sealed-secret-datavis-release
          - name: DBPASS
            valueFrom:
              secretKeyRef:
                key: dbpass
                name: sealed-secret-datavis-release
          - name: DBUSER
            valueFrom:
              secretKeyRef:
                key: dbuser
                name: sealed-secret-datavis-release
          args:
            {{- range .Values.datavis.prReminderChannelScheduler.args }}
            - {{ . }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
